steps:
  # Build backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/opcha-backend:$COMMIT_SHA'
      - './backend'
    id: 'build-backend'

  # Build frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/opcha-frontend:$COMMIT_SHA'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=https://opcha-backend-${_ENVIRONMENT}-${_RANDOM_SUFFIX}.a.run.app'
      - './frontend'
    id: 'build-frontend'

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/opcha-backend:$COMMIT_SHA'
    id: 'push-backend'

  # Push frontend image  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/opcha-frontend:$COMMIT_SHA'
    id: 'push-frontend'

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'opcha-backend-${_ENVIRONMENT}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/opcha-backend:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'RAILS_ENV=production,DATABASE_URL=${_DATABASE_URL}'
      - '--set-secrets'
      - 'RAILS_MASTER_KEY=RAILS_MASTER_KEY:latest'
    id: 'deploy-backend'

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'opcha-frontend-${_ENVIRONMENT}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/opcha-frontend:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    id: 'deploy-frontend'

substitutions:
  _ENVIRONMENT: 'prod'
  _REGION: 'asia-northeast1'
  _RANDOM_SUFFIX: '$(date +%s)'
  _DATABASE_URL: 'postgresql://user:password@/opcha_production?host=/cloudsql/PROJECT_ID:REGION:INSTANCE_NAME'

options:
  machineType: 'E2_HIGHCPU_8' 