version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: opcha_dev
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/opcha_dev
    ports:
      - "3001:3000"
    depends_on:
      - db
    volumes:
      - ./backend:/rails
  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
volumes:
  db-data:
# 本番環境ではCloud SQL(PostgreSQL)を利用し、dbサービスは不要 