version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: opcha_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Rails API Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: build
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/opcha_development
    volumes:
      - ./backend:/rails
      - bundle_cache:/usr/local/bundle
    ports:
      - "3001:80"
    depends_on:
      db:
        condition: service_healthy
    command: ["./bin/rails", "server", "-b", "0.0.0.0", "-p", "80"]

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: builder
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3001
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: ["npm", "run", "dev"]


volumes:
  postgres_data:
  bundle_cache:
  node_modules: